// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPaciente struct {
	ID       string `json:"id"`
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
	Paga     int    `json:"Paga"`
	Vsemana  int    `json:"Vsemana"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Paciente struct {
	ID       string `json:"id"`
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
	Paga     int    `json:"Paga"`
	Vsemana  int    `json:"Vsemana"`
}
