// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import(
	"gorm.io/gorm"
)


type Paciente struct {
	gorm.Model
	ID       string `gorm:"primary_key"`
	Nombre    string  `json:"nombre"`
	Apellido  string  `json:"apellido"`
	Vsemana   int     `json:"Vsemana"`
	Paga      int     `json:"Paga"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt"`
}



type PacienteInput struct {
	gorm.Model
	ID       string `gorm:"primary_key"`
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
	Vsemana  int    `json:"Vsemana"`
	Paga     int    `json:"Paga"`
}

/*
func(p*PacienteInput) BeforeCreateI(tx *gorm.DB) (err error) {
	p.ID = uuid.New()
	return
}
*/

type UpdatePaciente struct {
	Nombre   *string `json:"nombre"`
	Apellido *string `json:"apellido"`
	Vsemana  *int    `json:"Vsemana"`
	Paga     *int    `json:"Paga"`
}

type Terapista struct {
	ID        string  `json:"id"`
	Nombre    string  `json:"nombre"`
	Apellido  string  `json:"apellido"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt"`
}
