// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import(
	
	"gorm.io/gorm"
)


type Paciente struct {
    gorm.Model
    ID        string  `gorm:"primary_key"`
    Nombre    string  `json:"nombre"`
    Apellido  string  `json:"apellido"`
    Vsemana   int     `json:"vsemana"`
    Paga      int     `json:"paga"`
    CreatedAt string  `json:"createdAt"`
    UpdatedAt string  `json:"updatedAt"`
    DeletedAt *string `json:"deletedAt"`
}

type PacienteInput struct {
    Nombre   string `json:"nombre"`
    Apellido string `json:"apellido"`
    Vsemana  int    `json:"vsemana"`
    Paga     int    `json:"paga"`
}

type UpdatePaciente struct {
    Nombre   *string `json:"nombre"`
    Apellido *string `json:"apellido"`
    Vsemana  *int    `json:"vsemana"`
    Paga     *int    `json:"paga"`
}
type Terapista struct {
	ID        string  `json:"id"`
	Nombre    string  `json:"nombre"`
	Apellido  string  `json:"apellido"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt"`
}
